./index 1 ../../data/biz/temp/b ../../data/database/bizindex/b/ ../dict/easyseg/ &
./index 1 ../../data/biz/temp/c ../../data/database/bizindex/c/ ../dict/easyseg/ &
./index 1 ../../data/biz/temp/d ../../data/database/bizindex/d/ ../dict/easyseg/ &
./index 1 ../../data/biz/temp/e ../../data/database/bizindex/e/ ../dict/easyseg/ &
./index 1 ../../data/biz/temp/f ../../data/database/bizindex/f/ ../dict/easyseg/ &
./index 1 ../../data/biz/temp/g ../../data/database/bizindex/g/ ../dict/easyseg/ &
./index 1 ../../data/biz/temp/h ../../data/database/bizindex/h/ ../dict/easyseg/ &
./index 1 ../../data/biz/temp/i ../../data/database/bizindex/i/ ../dict/easyseg/ &
./index 1 ../../data/biz/temp/j ../../data/database/bizindex/j/ ../dict/easyseg/ &
